"""upgraded severity and type

Revision ID: 75bcff48d74e
Revises: 
Create Date: 2018-07-29 20:54:00.750292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bcff48d74e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_severity_name'), 'severity', ['name'], unique=True)
    op.create_index(op.f('ix_severity_weight'), 'severity', ['weight'], unique=False)
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_name'), 'type', ['name'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('guid', sa.String(length=32), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('severity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['severity_id'], ['severity.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_guid'), 'report', ['guid'], unique=False)
    op.create_index(op.f('ix_report_latitude'), 'report', ['latitude'], unique=False)
    op.create_index(op.f('ix_report_longitude'), 'report', ['longitude'], unique=False)
    op.create_index(op.f('ix_report_timestamp'), 'report', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_timestamp'), table_name='report')
    op.drop_index(op.f('ix_report_longitude'), table_name='report')
    op.drop_index(op.f('ix_report_latitude'), table_name='report')
    op.drop_index(op.f('ix_report_guid'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_type_name'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_severity_weight'), table_name='severity')
    op.drop_index(op.f('ix_severity_name'), table_name='severity')
    op.drop_table('severity')
    # ### end Alembic commands ###
